"""unique constraint on messages(conversation_id, seq)

Revision ID: 2c8820b050ba
Revises: 1ded42f9087d
Create Date: 2026-09-23 15:22:49.935598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8820b050ba'
down_revision: Union[str, Sequence[str], None] = '1ded42f9087d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_messages_conversation_seq', ['conversation_id', 'seq'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_messages_conversation_seq', type_='unique')

    # ### end Alembic commands ###
